apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::025555634459:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-ZMOAR68TSYFG
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::025555634459:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-21T07:05:52Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "18766"
  uid: 5162c59b-3564-4e74-8b9d-53f1ffaaa67a
